# Generated by Django 5.2.8 on 2025-11-30 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('amu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Амплуа')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='Контактная информация')),
            ],
            options={
                'verbose_name': 'Артист',
                'verbose_name_plural': 'Артисты',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=100, verbose_name='Название зала')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('type', models.CharField(choices=[('Струнные', 'Струнные'), ('Духовые', 'Духовые'), ('Язычковые', 'Язычковые'), ('Ударные', 'Ударные'), ('Перкуссия', 'Перкуссия'), ('Клавишные', 'Клавишные'), ('Электромузыкальные', 'Электромузыкальные')], max_length=50, verbose_name='Тип')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Инвентарный номер')),
                ('condition', models.CharField(choices=[('Отличное', 'Отличное'), ('Требует настройки', 'Требует настройки'), ('В ремонте', 'В ремонте')], default='Отличное', max_length=50, verbose_name='Состояние')),
            ],
            options={
                'verbose_name': 'Инструмент',
                'verbose_name_plural': 'Инструменты',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
        migrations.CreateModel(
            name='MusicalWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название произведения')),
                ('composer', models.CharField(max_length=255, verbose_name='Композитор')),
                ('duration', models.TimeField(blank=True, null=True, verbose_name='Продолжительность')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название произведения')),
                ('composer', models.CharField(blank=True, max_length=100, verbose_name='Композитор')),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(default='Планируется', max_length=50)),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concerts.hall')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.manager')),
            ],
        ),
        migrations.CreateModel(
            name='ConcertArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.artist')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.concert')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concerts.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(blank=True, max_length=255, verbose_name='Название программы')),
                ('concert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='concerts.concert', verbose_name='Концерт')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.IntegerField(default=1, verbose_name='Порядковый номер')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.program', verbose_name='Программа')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.musicalwork', verbose_name='Произведение')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
    ]
